### ISSUE TITLE
 How to create a transaction?

### ISSUE THREAD

**Issue by shawn0322** [kryptokrauts/aepp-sdk-java#4] opened 2019-02-18 06:47 UTC
What is the right way？

create:
final String fromAddress = "ak_gTFiAB8WWF99k6iGojuP5spZbUfngTackTfCVCB5BXu7866DA";
        final String privateKey = "de0084030a5cdaff40dc6b04f171c320ba1cbcbc567468a81f29949625922371599502335bd5512a475f2c5bd3b1402656c507a2483cdb73408188d0d11ebbb4";

        final String toAddress = "ak_2XrndsdSxSUQw1ZiJTdEEiMdDwJRtAyKeQ6ybT678vQDNyR6Tk";

        final TransactionService service = new TransactionServiceFactory().getService( TransactionServiceConfiguration.configure().baseUrl( "http://47.244.2.12:3013/v2/").compile() );
        final Single<UnsignedTx> spendTx = service.createSpendTx(fromAddress, toAddress,
                BigInteger.valueOf(100), "payload", BigInteger.valueOf(BaseConstants.DEFAULT_FEE), BigInteger.valueOf(11), BigInteger.valueOf(5));

        final Tx tx = service.signTransaction(spendTx.blockingGet(), privateKey);
        System.out.println(tx.getTx());

post ：http://47.244.2.12:3013/v2/transactions
{
    "reason": "Invalid tx"
}

**Comment by marc0olo** [comment] 2019-02-18 07:40
generally from the first view this seems to be correct. in which network are you trying to publish this transaction?

the standard configuration is pointing to the TESTNET. so if you are trying to publish this on mainnet you net to configure the TransactionServiceConfiguration to use Network.MAINNET.

**Comment by shawn0322** [comment] 2019-02-18 07:52
Thank you🙏. This key only exists in uat

**Comment by shawn0322** [comment] 2019-02-18 07:54
@marc0olo Thank you. This key only exists in uat

**Comment by marc0olo** [comment] 2019-02-18 08:04
does it work now? we’re you trying on mainnet?

**Comment by shawn0322** [comment] 2019-02-18 08:12
![image](https://user-images.githubusercontent.com/38547567/52936581-84a51380-3397-11e9-81ab-d0f916598e6e.png)

I encountered a NullPointerException on testnet

**Comment by marc0olo** [comment] 2019-02-18 08:18
seems like the WebClient couldn’t be initialized. could you test other testnet adresses or your own local testnet node?

But we should definitely provide a better Error if this is a problem with initializing the WebClient.

**Comment by shawn0322** [comment] 2019-02-18 08:57
I tested it on mainnet and testnet, but still can't work.

**Comment by marc0olo** [comment] 2019-02-18 08:59
I will have a look tonight. currently no time for it. thanks for reporting the issues!

**Comment by marc0olo** [comment] 2019-02-18 19:39
thx for reporting the issue. it seems like the problem is that there is some problem with the Vertx context
![image](https://user-images.githubusercontent.com/8124114/52973059-212ddc80-33bd-11e9-9e0b-812d1c8a50aa.png)

we will look into it!

I also got some dependency issues with google-guava when trying to reproduce your error. but that's another topic :-D

**Comment by marc0olo** [comment] 2019-02-19 00:12
@shawn0322 the issue should be solved now. we published a new release [v1.0.2](https://github.com/kryptokrauts/aepp-sdk-java/blob/v1.0.2/docs/release-notes/RELEASE-NOTES-1.0.2.md) and added a documentation how to generate and publish a transaction.

please check and let us know whether it works so that we can close this issue. thanks!

**Comment by shawn0322** [comment] 2019-02-19 06:42
I still didn't succeed when I copied the sample execution.

![image](https://user-images.githubusercontent.com/38547567/52994811-b7acdd00-3453-11e9-8f8a-0c8c3259bec6.png)

No problem with the interface
![image](https://user-images.githubusercontent.com/38547567/52994893-fe023c00-3453-11e9-82b1-1cf4bf0b44db.png)

**Comment by marc0olo** [comment] 2019-02-19 08:14
This seems more like a connection issue.

How often have you tried and how exactly does your configuration look like?

**Comment by shawn0322** [comment] 2019-02-19 14:36
it's OK now.I built a my own testnet（HTTP ，not HTTPS)，But I'm not sure  it's the reason.

Thanks for your timely reply 😄

**Comment by marc0olo** [comment] 2019-02-20 06:34
Glad it works now. Have fun! More features to come ;-)

**Closed by marc0olo** 2019-02-20 06:34 UTC
