### ISSUE TITLE
How to send a transaction

### ISSUE THREAD

**Issue by shenyaqi9527** [kryptokrauts/aepp-sdk-java#121] opened 2020-03-16 03:41 UTC
`
KeyPairService keyPairService = new KeyPairServiceFactory().getService();
        BaseKeyPair basekeyPair = keyPairService.generateBaseKeyPairFromSecret("f9dc85ad3fbdbcd957a281b7965bd29e7df4babda0c7842976a615714a0220a813f21016c148c17a1c9fcf4c5eb87d152b656d6276918c5f4903d0abf4bf1b74");

        AeternityService service = new AeternityServiceFactory()
                .getService(
                        AeternityServiceConfiguration.configure()
                                .baseUrl("https://testnet.aeternal.io")
                                .compilerBaseUrl("https://testnet.aeternal.io")
                                .aeternalBaseUrl("https://testnet.aeternal.io")
                                .network(Network.TESTNET)
                                .nativeMode(true)
                                .millisBetweenTrailsToWaitForConfirmation(500L)
                                .compile());
        AccountResult account = service.accounts.blockingGetAccount(Optional.of("ak_9nUzAM8NuC1UBvxEpLBrssqnMxjk1etQ2BwW95rfq46iRiSsu"));
        System.out.println(JSONObject.toJSONString(account));
        SpendTransactionModel spendTx =
                SpendTransactionModel.builder()
                        .sender(basekeyPair.getPublicKey())
                        .recipient("ak_spfGjJ9zz8cRg7aMNf1gMEVyAhVR4rS3AcENfQueNR7QL1NdJ")
                        .amount(new BigInteger("1000000000000000000"))
                        .payload("payload")
                        .ttl(new BigInteger("100"))
                        .nonce(account.getNonce().add(BigInteger.ONE))
                        .build();
        Single<StringResultWrapper> stringResultWrapperSingle = service.transactions.asyncCreateUnsignedTransaction(spendTx);

        String signTransaction = service.transactions.signTransaction(stringResultWrapperSingle.blockingGet().getResult(), basekeyPair.getPrivateKey());
        System.out.println(signTransaction);
        PostTransactionResult postTransactionResult = service.transactions.blockingPostTransaction(signTransaction);
        System.out.println(postTransactionResult.getTxHash());
`
exception
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
{"balance":5000000000000000000,"kind":"basic","nonce":0,"payable":true,"publicKey":"ak_9nUzAM8NuC1UBvxEpLBrssqnMxjk1etQ2BwW95rfq46iRiSsu"}
tx_+KoLAfhCuEAOI1nv/b+RjKzQH2fMODHI5QWiLlUmJ8cxLFgCU5rPYiz9x8pw+kEYIuYmnGUUGWArJPX1rqlRO9PwB71WpRsEuGL4YAwBoQET8hAWwUjBehyfz0xeuH0VK2VtYnaRjF9JA9Cr9L8bdKEBc2Wdlx3VVwoEu1ecKYRlFs3g/1RlvhbW2REzY+5y/G6IDeC2s6dkAACGD3F23kgAZAGHcGF5bG9hZIpnwwI=
三月 16, 2020 11:38:26 上午 io.vertx.core.impl.ContextImpl
严重: Unhandled exception
io.vertx.core.json.DecodeException: Failed to decode:Unrecognized field "reason" (class com.kryptokrauts.aeternity.generated.model.PostTxResponse), not marked as ignorable (one known property: "tx_hash"])
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 12] (through reference chain: com.kryptokrauts.aeternity.generated.model.PostTxResponse["reason"])
	at io.vertx.core.json.Json.decodeValue(Json.java:156)
	at com.kryptokrauts.aeternity.generated.ApiClient.lambda$buildResponseHandler$7(ApiClient.java:553)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:286)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:273)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:251)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:248)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:258)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:219)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:342)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "reason" (class com.kryptokrauts.aeternity.generated.model.PostTxResponse), not marked as ignorable (one known property: "tx_hash"])
 at [Source: (io.netty.buffer.ByteBufInputStream); line: 1, column: 12] (through reference chain: com.kryptokrauts.aeternity.generated.model.PostTxResponse["reason"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1179)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3250)
	at io.vertx.core.json.Json.decodeValue(Json.java:154)
	... 18 more`
Postman request

url:https://testnet.aeternal.io/v2/transactions
method : POST
body: 
`{"tx":"tx_+KoLAfhCuEAOI1nv/b+RjKzQH2fMODHI5QWiLlUmJ8cxLFgCU5rPYiz9x8pw+kEYIuYmnGUUGWArJPX1rqlRO9PwB71WpRsEuGL4YAwBoQET8hAWwUjBehyfz0xeuH0VK2VtYnaRjF9JA9Cr9L8bdKEBc2Wdlx3VVwoEu1ecKYRlFs3g/1RlvhbW2REzY+5y/G6IDeC2s6dkAACGD3F23kgAZAGHcGF5bG9hZIpnwwI="}`

response: 
`{
    "reason": "Invalid tx"
}`

@marc0olo

**Comment by mitch-lbw** [comment] 2020-03-16 09:05
Hi @shenyaqi9527,
the problem is the TTL you defined, which indicates the time amount a tx is valid. It's recommended to set it to zero or at least a big amount of time. You also can shortcut the transaction posting (unless you explicitly need the unsigned tx):
`PostTransactionResult postTransactionResult = service.transactions
				.blockingPostTransaction(spendTx, basekeyPair.getPrivateKey());`

Greetings,
Mitch

**Comment by shenyaqi9527** [comment] 2020-03-16 09:20
Thanks

**Comment by marc0olo** [comment] 2020-03-16 19:55
closing this now. if you have any other issues let us know! :-)

**Closed by marc0olo** 2020-03-16 19:55 UTC
Labels: question
